#include <avr/io.h>
#include <stdbool.h>

void Fun_TWI_Initialization (void) {
	
	PORTA.DIRSET = PIN2_bm | PIN1_bm;
	PORTA.PIN1CTRL = (0<<PORT_INVEN_bp) | (0<<PORT_PULLUPEN_bp) | PORT_ISC_INTDISABLE_gc;
	PORTA.PIN2CTRL = (0<<PORT_INVEN_bp) | (0<<PORT_PULLUPEN_bp) | PORT_ISC_INTDISABLE_gc;	
	PORTMUX.CTRLB |= PORTMUX_TWI0_bm;
	
	
	TWI0.DBGCTRL = (1<<TWI_DBGRUN_bp);
	TWI0.CTRLA = TWI_SDASETUP_8CYC_gc | TWI_SDAHOLD_500NS_gc | (0<<TWI_FMPEN_bp);
	TWI0.MBAUD = ((20000000.0/100000.0)-10.0)/2.0;
	TWI0.MCTRLB = TWI_FLUSH_bm | TWI_MCMD_NOACT_gc;
	TWI0.MCTRLA = (0<<TWI_RIEN_bp) | (0<<TWI_WIEN_bp) | (0<<TWI_QCEN_bp) | TWI_TIMEOUT_DISABLED_gc | (0<< TWI_SMEN_bp) | (1<<TWI_ENABLE_bp);
	TWI0.MSTATUS = TWI_BUSSTATE_IDLE_gc;
	
		
}